modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/shedaniel/LightOverlay/issues/" #optional
logoFile = "icon.png"
authors = "shedaniel"
license = "Apache-2.0"
[[mods]]
modId = "lightoverlay"
version = "${version}"
displayName = "Light Overlay"
description = '''
To provide users with NEI-like light overlay.
'''

[[dependencies.lightoverlay]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lightoverlay]]
modId = "architectury"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "CLIENT"
